### ISSUE TITLE
Improve initial zoom of examples

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomvizweb#1]
Is there an easy way for us to improve the initial zoom, things look pretty tiny but improve once you zoom in quite a bit more.

**Comment by jourdain** [comment]
Not as right now. But you could imagine using the following attribute `data-initialization="zoom=1.2"`

**Comment by jourdain** [comment]
It will be a 5 minutes fix and 10 minutes wait time for the new version to get published. Let's stack all your feedback so I can batch process them all at once.

Like later this afternoon or tomorrow.

**Comment by cryos** [comment]
Sounds good, that is why I thought we could use an issue to track it. Something as you suggest would be ideal.

**Comment by jourdain** [comment]
Done as well.
