### ISSUE TITLE
tomvizweb description not shown properly

### ISSUE THREAD

**Issue by agirault** [OpenChemistry/tomvizweb#3]
On Google Chrome 57.0.2987.98 (64-bit), macOS Sierra.

This text ([Documentation/content/index.jade#L40-L44](https://github.com/OpenChemistry/tomvizweb/blob/76c716cf14f97322e877dc0b5e0677f17a3ab581/Documentation/content/index.jade#L40-L44)) :
```
p
  Fully interactive, WebGL-based export of tomographic data. Double-click to
  stop the animation, left-click to rotate, shift + left-click to pan, and
  ctrl + shift + left-click to zoon. Click the button in the top-right to
  interact with the color map or opacity values of the transfer function.
```

Appears as such (missing first words of each new lines):

>interactive, WebGL-based export of tomographic data. Double-click tothe animation, left-click to rotate, shift + left-click to pan, and+ shift + left-click to zoon. Click the button in the top-right towith the color map or opacity values of the transfer function.

Also: typo for zoom (zoon)

<img width="1304" alt="screen shot 2017-03-30 at 9 36 48 am" src="https://cloud.githubusercontent.com/assets/4910855/24506807/a9779704-152c-11e7-936e-5d60b0b5a5b5.png">

**Comment by cryos** [comment]
Thanks, I will take a look, I wanted to add some instructions but may not have inserted the text into the template correctly.

**Comment by jourdain** [comment]
Everything should be fine now.
