### ISSUE TITLE
 Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by mrakitin** [OpenChemistry/tomvizweb#4]
We together with @yxqd are trying to implement tomvizweb visualization in Jupyter notebooks (please see https://github.com/scikit-beam/ipywe). We met a problem when attempting to visualize two objects:
![image](https://user-images.githubusercontent.com/13209176/32847542-42e94dee-c9f8-11e7-9a9f-ba7e10c83cfc.png)

## Steps to reproduce:
- Prepare the environment:
```bash
$ git clone https://github.com/scikit-beam/ipywe
$ cd ipywe
$ conda create -n ipywe python=3
$ source activate ipywe
$ ./dev_js_update.sh
# Start Jupyter:
$ jupyter notebook --port=8000
```
- Open http://localhost:8000/notebooks/tests/test_tomvizjs.ipynb and run all cells.
- Run the cell `ipywe.tomvizjs.TomvizJs(url='https://openchemistry.github.io/tomvizweb/data/GeometryContourExploration.tomviz')` one more time.
- Check browser console log.

I hope it can be fixed soon. We don't observe problems with vtk.js visualization of multiple objects in different cells (try http://localhost:8000/notebooks/tests/test_vtkjs.ipynb).

**Comment by cryos** [comment]
@jourdain do you have any ideas on what is wrong here?

**Comment by jourdain** [comment]
Yes, I've added the polyfill inside tomviz-web to make it work on "old" browsers. 

But when inside the notebook, Jupyter already provide the polyfill, so by loading tomviz-web we load that library twice.

To fix it, we should remove it from tomviz-web. But when embedding in web pages that don't already load the polyfill, we should add the polyfill script along with the  tomviz-web one.

**Comment by jourdain** [comment]
Remove that line

https://github.com/OpenChemistry/tomvizweb/blob/master/Source/tomviz-viewer.js#L7

Then when doing that https://openchemistry.github.io/tomvizweb/docs/
we should have both scripts

```
<script type="text/javascript" src="https://unpkg.com/babel-polyfill/dist/polyfill.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/tomvizweb"></script>
```

**Comment by cryos** [comment]
Thanks @jourdain for explaining, I will take a look and try to get something pushed when I get a chance.

**Comment by cjh1** [comment]
@mrakitin Sorry for the delay, this issue is now resolved in the latest release of tomvizweb, see screenshot below. Thanks for the excellent instructions for the recreate. 

![screen](https://user-images.githubusercontent.com/1031053/38886323-9d352106-4243-11e8-8849-26a8b8fbe813.png)

**Comment by mrakitin** [comment]
@cjh1, thank you for resolving the issue, this is a really useful fix!
